# do not use "latest" here, if you want this to work in the future
# cài gitlab-runner, docker,git, nodejs, pm2 lên server
# cho user gitlab-runner quyền sudo, usermod -aG docker gitlab-runner

image: docker:24

services:
  - docker:dind

stages:
  - deploy-development

before_script:
  - docker version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

deploy-development:
  stage: deploy-development
  only:
    - develop
  tags:
    - dev-api.akaiunsan.vn
  script:    
    - sudo rsync -arz . /home/dev-api.akaiunsan.vn  
    - cd /home/dev-api.akaiunsan.vn
    - sudo npm install --development --silent  
    - sudo /usr/local/bin/pm2 delete all
    - sudo  /usr/local/bin/pm2 startup
    - sudo /usr/local/bin/pm2 start app.js --env development --watch 
    - sudo /usr/local/bin/pm2 save 
    - sudo /usr/local/bin/pm2 status



   

    
